### ISSUE TITLE
Player doesn't feel like it has weight to it

### ISSUE THREAD

**Issue by sb7766** [Stamaia-Studios/2dplatformer#10]
Basically just a new issue for the first half of #8.

> As of currently there doesn't have any feeling of weight to the player object.
It shouldn't be significant, but a half second acceleration period when pressing the run button should feel more natural and place more 'weight' to the character. A very quick deceleration would aid this purpose as well at the end of motion, but only when recovering from the running state. These two will also make the ability to turn around and run feel less odd."

**Comment by NyaSeiru** [comment]
On top of this, the acceleration/deceleration should hopefully allow being able to control air movement. Right now it's impossible to stay still in the air.

Currently movement speed is static in air, to improve responsiveness, normal jump should allow fine control. Running jump can keep the forward momentum and require deceleration from the player to return to neutral horizontal speed.
