### ISSUE TITLE
Prototype Tiles should be set to 24x24px

### ISSUE THREAD

**Issue by NyaSeiru** [Stamaia-Studios/2dplatformer#16]
Better now than later, 24px has been decided as the tile-size decision.

Optionally noting, building the room is extremely awkward with the tile origins being placed at the center. Consider testing having the tiles with origin at top-left.

**Comment by sb7766** [comment]
Duly noted. Since I wrote most of the collision code, I'll go ahead and see if changing the tiles like that works, or if there's a way to make it look nicer in the map editor.

Also, do you want the player sprites to be adjusted accordingly?

**Comment by NyaSeiru** [comment]
That may be considered.

The player sprite may be changed to 24x32px collision box. Since it's safer to keep with a tile system in regards to crawl/slide space, a smaller tile object should be used as a crawling ceiling to place under a wall object. This shouldn't 'cause any collision issue.

If we give a bit of headroom to the player object, it should remove the second issue currently where the Player does not return to a standing state if the space has no leeway.

**Comment by sb7766** [comment]
I'll work on this in the morning and test everything out.
