### ISSUE TITLE
Two Notices: Running Speed & Current Dash Attack Cooldown feels Unnatural

### ISSUE THREAD

**Issue by NyaSeiru** [Stamaia-Studios/2dplatformer#8]
As of currently there doesn't have any feeling of weight to the player object.
It shouldn't be significant, but a half second acceleration period when pressing the run button should feel more natural and place more 'weight' to the character. A very quick deceleration would aid this purpose as well at the end of motion, but only when recovering from the running state. These two will also make the ability to turn around and run feel less odd.

The Dash Attack should finish it's animation and not be cancel-able into a jump or slide for balance purposes.

As of currently also, the Dash Attack has a cooldown but it feels arbitrary and may be confusing to players. If you wish to prevent multiple dash attacks from 'causing an unintended fast action/movement from the player, the dash attack should be approached by two alternate methods instead.

A. The Dash attack provides the maximum speed as a boost, allowing impact for the attack. However the animation extends and decelerates to a halt/walking speed before allowing the player to run again. This should prevent the attack from being any more useful than a melee chain for offensive purposes or just running without interruption for movement purposes.

OR

B. The Dash attack continues at the same momentum that the player object was currently in, with a minimum speed if needed to still feel natural with the planned animation. This may be used to skip the half second acceleration period but shouldn't 'cause any overall issues.

The following two mp4s demonstrate some of what I'm addressing above.
[Quick Turnaround + Jump Dash Attack](https://i.gyazo.com/f01deb9a799a2ee61016f72251962005.mp4)
[Crouch Dash Attack](https://i.gyazo.com/4d5cef82332bac6ffd20208d6a7b0aa1.mp4)

**Comment by minimummums** [comment]
Created PR for dash problems

**Comment by Wolvan** [comment]
@minimummums you can directly link the PR/Issues in question by just using their number like so #9.

Also, if you add a `Closes #8` to your PR OP, Github should automatically close this issue once the PR is merged
